
title: Learning Statistics with Python
author: Danielle Navarro and Ethan Weed

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    - references.bib

bibtex_reference_style: author_year

repository:
  url: https://github.com/ethanweed/pythonbook
  branch: https://github.com/ethanweed/pythonbook/tree/main/Chapters

html:
  use_issues_button: true
  use_repository_button: true


parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
